# Humidity Control
#

blueprint:
  name: Room Humidity Control
  description: Control a rooms humidity level with a fan or dehumidifier.
  domain: automation
  source_url: https://github.com/JunkCoding/homeassistant-blueprints/blob/main/humidity_control.yaml
  input:
    humidity_sensor:
      name: Humidity Sensor 
      description: Humidity sensor, ideally located in the room of the fan or dehumidifier
      selector:
        entity:
          domain:
            - sensor
    fan_switch_target:
      name: Fan Switch
      selector:
        target:
          entity:
            domain:
              - switch
              - fan
    humidity_percent_to_start:
      name: Turn on at percent humidity
      description: What humidity percentage to turn on.
      default: 58
      selector:
        number:
          min: 1
          max: 100
          step: 1
          unit_of_measurement: percent
    humidity_percent_to_stop:
      name: Turn off at percentage humidity
      description: What humidity percentage to turn off.
      default: 50
      selector:
        number:
          min: 1
          max: 100
          step: 1
          unit_of_measurement: percent

mode: restart
max_exceeded: silent

trigger:
  - platform: numeric_state
    entity_id: !input humidity_sensor
    above: !input humidity_percent_to_start
    below: '100'

action:
  - service: switch.turn_on
    target: !input fan_switch_target
  - service: switch.turn_off
    target: !input fan_switch_target

