# Humidity Control
#

blueprint:
  name: Room Humidity Control
  description: Switch on a fan or dehumidifier to control a rooms humidity level.
  domain: automation
  source_url: https://github.com/JunkCoding/homeassistant-blueprints/blob/main/humidity_control.yaml
  input:
    humidity_sensor:
      name: Humidity Sensor 
      description: Humidity sensor, ideally located in the room of the fan or dehumidifier
      selector:
        entity:
    humidity_percent_to_start:
      name: Turn on at, value
      description: What humidity percentage to turn on.
      default: 58
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: percent
    fan_switch_target:
      name: Fan Switch
      selector:
        target:
          entity:
            domain: switch

    humidity_percent_to_stop:
      name: Turn on off, value
      description: What humidity percentage to turn off.
      default: 50
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: percent

trigger:
  - platform: numeric_state
    entity_id: !input humidity_sensor
    above: !input humidity_percent_to_start
    below: '100'

action:
  - service: switch.turn_on
    target: !input fan_switch_target
  - service: switch.turn_off
    target: !input fan_switch_target

mode: restart
max_exceeded: silent
